version: '3'

services:
    registry:
        restart: unless-stopped
        image: registry:2
        ports:
            - 443:5000
        environment:
            - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
            - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
            # - REGISTRY_AUTH: htpasswd
            # - REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            # - REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        volumes:
            - /path/data:/var/lib/registry
            - /etc/letsencrypt/live/clusterimages.fun:/certs
